### ISSUE TITLE
Update Task Log Display

### ISSUE THREAD

**Issue by aclowery** [bcgov/ExitSurveyAdmin#189] opened 2023-01-10 20:12 UTC
Align with NJSA:
- Add Task filter
- ~Display most recent to oldest (Exit currently oldest to newest)~ See #184 for this one.

**Comment by hangler** [comment] 2023-02-20 19:01
The second item is a duplicate of #184 and is fixed there.

**Comment by aclowery** [comment] 2023-02-23 20:18
Confirming the Task filter is now there

**Closed** 2023-02-24 00:24 UTC
Labels: ✓ enhancement, interface, fixed on branch
